---
 - name: install nginx
   shell: yum update && amazon-linux-extras \
           install nginx1 -y
   become: yes

 - name: install python-pip
   yum:
    name: python-pip
    state: present
    update_cache: true
   become: yes

 - name: install virtualenv
   shell: pip install virtualenv
   become: yes   

 - name: setup application directory
   file:
    path: "{{ app_dir }}"
    state: directory
    owner: "{{ execution_user }}"
    group: "{{ execution_user }}"
    mode: "{{ folder_permission }}"
   become: yes
   
 - name: copy application files
   copy:
    src: "{{ item }}"
    dest: "{{ app_dir }}/{{ item }}"
    owner: "{{ execution_user }}"
    group: "{{ execution_user }}"
    mode: "{{ folder_permission }}"
   loop: "{{ application_files }}"
   become: yes
 
 - name: update permissions
   file:
    path: "{{ app_dir }}/{{ item }}"
    owner: "{{ execution_user }}"
    group: "{{ execution_user }}"
    mode: "{{ folder_permission }}"
   loop: "{{ application_files }}" 
 
 - name: initialize virtual environment
   shell: virtualenv env   
   args:
    chdir: "{{ app_dir }}"
   become: yes

 - name: install dependencies
   shell: source env/bin/activate && \
          pip install flask
   args:
    chdir: "{{ app_dir }}"
   become: yes

 - name: copy application service in systemd
   copy:
    src: "{{ application_service }}"
    dest: "/etc/systemd/system/{{ application_service }}"    
   become: yes

 - name: copy nginx conf
   copy:
    src: "nginx.conf"
    dest: "{{ nginx_conf_dir }}"    
   become: yes

 - name: Enable application services
   service:
    name: "{{ item }}"
    enabled: true
    masked: no
   loop: "{{ application_service_to_restart}}"
   become: yes


 - name: restart application services
   service:
    name: "{{ item }}"
    state: restarted
   loop: "{{ application_service_to_restart}}"
   become: yes
